services:
  neo4j:
    image: 'neo4j:5.23.0-community-bullseye'
    restart: always
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./data:/data
      - ./data.csv:/var/lib/neo4j/import/data.csv
    environment:
      NEO4J_AUTH: none
